[project]
name = "h8-112-rmt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "numpy>=2.2.0",
    "pandas>=2.2.3",
    "ruff>=0.8.0",
]
